// AUTO-GENERATED by generateFieldMap.mjs
// Edit per-field properties here (width/fontSize/etc)

export type FieldSpec = {
  pageIndex: number;
  x: number;
  y: number;
  width?: number;
  height?: number;
  fontSize?: number;
  lineHeight?: number;
  align?: "left" | "center" | "right";
  maxFontSize?: number;
  minFontSize?: number;
  clearBackground?: boolean;
};

export type FieldMap = Record<string, FieldSpec>;

export const fieldMap: FieldMap = {
  "firstName": { pageIndex: 0, x: 337.5, y: 639.42, fontSize: 12, clearBackground: false },
  "idNumber": { pageIndex: 0, x: 341.25, y: 593.17, fontSize: 12, clearBackground: false},
  "lastName": { pageIndex: 0, x: 338.75, y: 616.92, fontSize: 12, clearBackground: false },
};
