// AUTO-GENERATED by generateFieldMap.mjs
// Edit per-field properties here (width/fontSize/etc)

export type Direction = "auto" | "ltr" | "rtl";

export type FieldSpec = {
  pageIndex: number;
  x: number;
  y: number;
  direction?: Direction;
  width?: number;
  height?: number;
  fontSize?: number;
  lineHeight?: number;
  align?: "left" | "center" | "right";
  maxFontSize?: number;
  minFontSize?: number;
  clearBackground?: boolean;
};

export type FieldMap = Record<string, FieldSpec>;

export const fieldMap: FieldMap = {
  "firstName": { pageIndex: 0, x: 402.84, y: 641.48, direction: "rtl", fontSize: 12, clearBackground: false },
  "idNumber": { pageIndex: 0, x: 403.51, y: 592.81, direction: "rtl", fontSize: 12, clearBackground: false },
  "lastName": { pageIndex: 0, x: 398.18, y: 618.54, direction: "rtl", fontSize: 12, clearBackground: false },
};
